"""empty message

Revision ID: bb8421be5f7d
Revises: 
Create Date: 2023-11-20 11:09:36.311294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8421be5f7d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus',
    sa.Column('bus_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bus_name', sa.String(length=50), nullable=False),
    sa.Column('bus_route', sa.String(length=50), nullable=False),
    sa.Column('information', sa.String(length=13), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('bus_id')
    )
    op.create_table('alert',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bus_id', sa.BigInteger(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['bus.bus_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert')
    op.drop_table('bus')
    # ### end Alembic commands ###
